name: update CV

on:
  push:
    branches: ["master"]
    
    paths:
      - 'static/CV/index.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Makefile directory
      run: |
        cd static/CV
        echo "Makefile directory set to $(pwd)"
    
    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt install texlive-xetex latex-cjk-all
        sudo apt-get install fonts-noto
        sudo apt-get install texlive-fonts-extra

        
    - name: Run Makefile
      run: make
      working-directory: static/CV